### ISSUE TITLE
PosixPath has no attribute `rfind`

### ISSUE THREAD

**Issue by mweinelt** [mweinelt/aurblobs#7]
```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
```

```
$ ls -lah ~/.config/aurblobs/
total 16K
drwxr-xr-x 2 aurpkg nogroup 4.0K Dec  4 18:10 .
drwxr-xr-x 3 aurpkg nogroup 4.0K Dec  4 18:10 ..
-rw-r--r-- 1 aurpkg nogroup  500 Dec  4 18:10 prebuilt.gpg
-rw-r--r-- 1 aurpkg nogroup   91 Dec  4 18:12 prebuilt.json
```

```
$ aurblobs list
Traceback (most recent call last):
  File "/var/lib/aurpkg/.local/bin/aurblobs", line 11, in <module>
    sys.exit(cli())
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/aurblobs/cli.py", line 52, in _list
    in Path(CONFIG_DIR).glob('*.json')
  File "/var/lib/aurpkg/.local/lib/python3.5/site-packages/aurblobs/cli.py", line 51, in <listcomp>
    for repofile
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'PosixPath' object has no attribute 'rfind'
```

**Comment by sweisgerber-dev** [comment]
281a451 : that helped me :+1:

Python 3.5 needed a string for path, while Python 3.6+ happily accepts PosixPaths

**Comment by seppowalther** [comment]
Thank you, that helped a lot.

Had the issue in a different situation and Google lead me to this issue, maybe this can help someone else experiencing this issue.

Using Python FPDF I tried:

```
template2page1path = (base_path / "resources/images/newtemplate2_seite1.jpg").resolve()
pdf.image(template2page1path, x=-4, y=-8, w=217, h=313)
```

What fixed the problem was:

```
template2page1path = (base_path / "resources/images/newtemplate2_seite1.jpg").resolve()
pdf.image(str(template2page1path), x=-4, y=-8, w=217, h=313)
```
